# Generated by Django 6.0.6 on 2026-06-15 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_viagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_viagem', models.DateTimeField(blank=True, null=True)),
                ('rastro_gps', models.TextField(default='[]', help_text='Coordenadas JSON de latitude e longitude')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='sitrev.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='sitrev.veiculo')),
            ],
        ),
    ]
